### ISSUE TITLE
tmweb: no sockets and no logs

### ISSUE THREAD

**Issue by cbaakman** [dennyverbeeck/transmart-docker#8]
I've built transmart-docker from the master branch. tmweb keeps restarting with the following errors:
```
[Thu Apr 16 08:49:33.644125 2020] [proxy_html:notice] [pid 1:tid 140336759250248] AH01425: I18n support in mod_proxy_html requires mod_xml2enc. Without it, non-ASCII characters in proxied pages are likely to display incorrectly.
(98)Address in use: AH00072: make_sock: could not bind to address [::]:80
(98)Address in use: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs
```

Could someone help me fix this?

My docker-compose looks like this:
```
version: '2'

services:
  tmweb:
    image: httpd:alpine
    restart: unless-stopped
    network_mode: host
    expose:
      - "80"
    ports:
      - "127.0.0.1:8888:80"
    depends_on:
      - tmapp
    volumes:
      - "./transmart-web/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf"
      - "./transmart-web/httpd.conf:/usr/local/apache2/conf/httpd.conf"
  tmapp:
    image: dennyverbeeck/transmart-app:etriks-v4.0
    restart: unless-stopped
    ports:
      - "127.0.0.1:8009:8009"
    depends_on:
      - tmdb
      - tmsolr
      - tmgwava
    volumes:
      - "./transmart-app/Config.groovy:/root/.grails/transmartConfig/Config.groovy"
      - "./transmart-app/DataSource.groovy:/root/.grails/transmartConfig/DataSource.groovy"
      - "./transmart-app/setenv.sh:/usr/local/tomcat/bin/setenv.sh"
      - "appdata:/root/.grails"
      - "apptmp:/tmp"
      - "appwebapps:/usr/local/tomcat/webapps"
  tmgwava:
    image: dennyverbeeck/transmart-gwava:tmf-16.2
    restart: unless-stopped
  tmdb:
    image: dennyverbeeck/transmart-db:etriks-v4.0
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "postgresdata:/var/lib/postgresql"
      - "postgreslogs:/var/log/postgresql"
  tmsolr:
    image: dennyverbeeck/transmart-solr:etriks-v4.0
    restart: unless-stopped
  tmrserve:
    image: dennyverbeeck/transmart-rserve:etriks-v4.0
    restart: unless-stopped
    volumes:
      - "apptmp:/tmp"
      - "appwebapps:/usr/local/tomcat/webapps"
  tmload:
    image: dennyverbeeck/transmart-load:etriks-v4.0
    depends_on:
      - tmdb

volumes:
  appdata:
  apptmp:
  appwebapps:
  postgresdata:
 postgreslogs:
```
